### ISSUE TITLE
Baseline

### ISSUE THREAD

**Issue by meneal** [shaowns/CSC791MLUAS_Project#11]
We need the code finished up for the baseline so we can use it in our demo later this week.  What kind of timeline are we looking at for that being completed?

**Comment by nvinchh** [comment]
Hey guys. Sorry about that. A few personal issues had come up. I've started working on it. Will try my best to complete it by tonight or tomorrow

**Comment by meneal** [comment]
No worries dude.  As long as it's done tomorrow we shouldn't have a huge problem getting the data we need.  let me know if you have any questions about how the logger works, or anything like that.

**Comment by botwithfeelings** [comment]
Removing this from April 7 demo.

**Comment by botwithfeelings** [comment]
Closing as we have baseline results.
