### ISSUE TITLE
Baseline getting high accuracy

### ISSUE THREAD

**Issue by nvinchh** [shaowns/CSC791MLUAS_Project#13]
Getting an insanely high accuracy for the baseline algorithm when num_recs=10.
When changed it to 5, it reduces, still higher than our implementation. Have commented the code to make it easier to understand what I've done. Please have a look when you have time to confirm if I've understood and implemented the baseline algorithm correctly. 
The file is baseline.py

**Comment by botwithfeelings** [comment]
I think this has been resolved with my update to baseline, closing.
