### ISSUE TITLE
Add cross validation for item-based cf

### ISSUE THREAD

**Issue by botwithfeelings** [shaowns/CSC791MLUAS_Project#4]

**Comment by meneal** [comment]
Based on our conversation today with Dr. Chi we will want to do K-Folds cross validation with K=14.  for each user in the test set we will randomly select an attribute as y and attempt to predict it.  I can take this on.  I'll try to get to it at some point this weekend.  I have an algo exam next week on Tuesday, so worst case I'll work on this after that.

**Comment by meneal** [comment]
So I've started on this tonight, I used what you've done so far, but there's some weirdness.  There was a use of a generator in utility.py for the gen_chunks function that messed up a bunch of other stuff, so I just switched it to a list.  I tried just putting dots in to show progress, but I'm not sold that it's really useful to do that.  I tend to like having something that shows whether a program is hung or not.

I made enough other small changes to the point that on each fold the program should spit out some output to indicate the ratio of successes to the number of test elements.  It takes a long time to run each one prob 5-10 minutes.  I just ran the first one for testing purposes and got an odd value though: 65%.  Not sure completely what to think of that.

Probably more bugs in there.

**Comment by meneal** [comment]
This is mostly done and now includes a logger for running test cases.  As soon as #10 is closed I think we can run these and finish this out.  I have a node on Digital Ocean running right now that I'm running the tests on.  It's much easier since that way I don't have to tie up my machine running this shit.

**Comment by meneal** [comment]
I think this is completely done.  Let me know if anyone sees any issues.  If not I'll close.

**Comment by botwithfeelings** [comment]
Closing this.
