### ISSUE TITLE
Add vector extraction from Fuse data

### ISSUE THREAD

**Issue by botwithfeelings** [shaowns/CSC791MLUAS_Project#5]

**Comment by botwithfeelings** [comment]
This is done. Will close based on feedback.

The user key at this moment is: created_by(POI)#last_modified_by(POI)#internet_domain_name(DOMAIN)

Both the raw user vectors and the weighted vectors are dumped using pickle. The tuning weight factor for tf-idf at this moment is 10.

**Comment by meneal** [comment]
Isn't this done?  What do we need to determine about this to close?

**Comment by botwithfeelings** [comment]
Closing this.
