### ISSUE TITLE
Add feature vector extraction from user input

### ISSUE THREAD

**Issue by botwithfeelings** [shaowns/CSC791MLUAS_Project#6]
Not sure this should be part of our April 1 milestone. Comments?

**Comment by meneal** [comment]
Is this the idea of adding in an excel plugin?

**Comment by botwithfeelings** [comment]
Yes, but I am slowly coming to the realization that this might be out of scope for this course.

**Comment by botwithfeelings** [comment]
Out of scope. Maybe in some distant future, maybe....
