### ISSUE TITLE
User-cf has lots of empty recommendations for Fuse users

### ISSUE THREAD

**Issue by botwithfeelings** [shaowns/CSC791MLUAS_Project#8]
The features extracted are often very short (three or less function usage), and a number of these result in no recommendation in the user-based CF, even with a large no of similar vectors. Should we decide on a threshold for recommending anything for such vectors?

PS. the item-based cf will probably chew out something always. Could this result in a disparity between the cross validation results?

**Comment by meneal** [comment]
This might well be an issue to discuss with Dr. Chi.  What do you think?
